# Generated by Django 2.1.1 on 2018-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='file',
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='cookie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='cookie',
            name='description',
            field=models.TextField(default='description', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
